// Grammar for an Objective Stage

?start: sum

?sum: product
    | sum "+" product   -> add
    | sum "-" product   -> sub

?product: atom
    | product "*" atom  -> mul
    | product "/" atom  -> div

?atom: NUMBER           -> number
     | NAME             -> var
     | "-" atom         -> neg
     | "(" sum ")"
     | NAME"("args")"   -> func

args: [sum ("," sum)*]

%import common.CNAME -> NAME
%import common.NUMBER
%import common.WS_INLINE

%ignore WS_INLINE
